# target-esp32.mk — shared ESP-IDF (idf.py) build rules for the esp32 projects.
#
# A project Makefile sets the variables below, then includes this file:
#   PLATFORM      target chip, e.g. esp32c3                 [required]
#   NAME          app name; TARGET = build/$(NAME).bin      [default: app]
#   SOURCES       files whose change should force a rebuild  [default: main/$(NAME).c]
#   DEVICE        serial port for flash / monitor           [default: /dev/ttyACM0]
#   BUILDER_DEFS  extra `idf.py -D...` cache entries         [optional]
#
# `make release` builds a lean field / OTA image into $(RELEASE_DIR) (default
# build_release/): ESP_LOG compiled out and assertions silenced, so the format
# strings drop out of flash. Kept entirely separate from the verbose build/.
#
# Source paths come from iotdata-common/make/config.mk — include that first so
# BUILDER_DEFS can reference the SRC_* variables.

BUILDER      ?= idf.py
NAME         ?= app
SOURCES      ?= main/$(NAME).c
DEVICE       ?= /dev/ttyACM0
BUILDER_DEFS ?=
BUILDER_CFGS ?= build/build.ninja
TARGET       ?= build/$(NAME).bin

# release image: the dev sdkconfig.defaults is the single source of truth; the release
# config is SYNTHESISED from it on the fly (see the `release` rule) into a separate dir.
SDKCONFIG_DEFAULTS ?= sdkconfig.defaults
RELEASE_DIR        ?= build_release
RELEASE_DEFAULTS   ?= $(RELEASE_DIR)/sdkconfig.defaults

.DEFAULT_GOAL := all
.PHONY: all upload debug monitor size setup clean fullclean format release release-size release-upload

all: $(TARGET)

$(TARGET): $(SOURCES) $(BUILDER_CFGS)
	$(BUILDER) $(BUILDER_DEFS) build

$(BUILDER_CFGS):
	$(BUILDER) set-target $(PLATFORM)

# Lean field / OTA image, into a SEPARATE $(RELEASE_DIR) so it never touches build/.
# ESP_LOG is stripped at COMPILE time (drops the format strings from flash — ~18%
# smaller in practice) and assertions are silenced. The release sdkconfig.defaults is
# SYNTHESISED from $(SDKCONFIG_DEFAULTS): the log / assertion / target lines are removed
# and re-set. It is a full derivation, NOT a layered overlay, because a layered overlay
# cannot flip the LOG_MAXIMUM_LEVEL choice (an ESP-IDF quirk) and that is the switch that
# actually removes the strings. Regenerated every run; the source of truth stays the one
# committed $(SDKCONFIG_DEFAULTS). Version stamping is a later TODO.
release:
	@test -f $(SDKCONFIG_DEFAULTS) || { echo "release: no $(SDKCONFIG_DEFAULTS) to derive from"; exit 1; }
	@mkdir -p $(RELEASE_DIR)
	@grep -vE '^CONFIG_(IDF_TARGET|LOG_MAXIMUM_LEVEL|LOG_DEFAULT_LEVEL|COMPILER_OPTIMIZATION_ASSERTION)' $(SDKCONFIG_DEFAULTS) > $(RELEASE_DEFAULTS)
	@printf '\n# --- release overrides (generated by make release; do not edit) ---\n' >> $(RELEASE_DEFAULTS)
	@printf 'CONFIG_IDF_TARGET="$(PLATFORM)"\n'                     >> $(RELEASE_DEFAULTS)
	@printf 'CONFIG_LOG_DEFAULT_LEVEL_NONE=y\n'                     >> $(RELEASE_DEFAULTS)
	@printf 'CONFIG_LOG_MAXIMUM_LEVEL_NONE=y\n'                     >> $(RELEASE_DEFAULTS)
	@printf 'CONFIG_COMPILER_OPTIMIZATION_ASSERTIONS_SILENT=y\n'    >> $(RELEASE_DEFAULTS)
	$(BUILDER) -B $(RELEASE_DIR) -D SDKCONFIG=$(RELEASE_DIR)/sdkconfig -D SDKCONFIG_DEFAULTS=$(RELEASE_DEFAULTS) $(BUILDER_DEFS) build
	@echo ""
	@echo "release image: $$(ls $(RELEASE_DIR)/*.bin 2>/dev/null)"
release-size:
	$(BUILDER) -B $(RELEASE_DIR) size
release-upload:
	$(BUILDER) -B $(RELEASE_DIR) flash -p $(DEVICE)

upload:
	$(BUILDER) flash -p $(DEVICE)
debug:
	$(BUILDER) flash -p $(DEVICE) monitor
monitor:
	$(BUILDER) -p $(DEVICE) monitor
size:
	$(BUILDER) size
setup:
	@echo "try . $(IDF_PATH)/export.sh"
clean:
	$(BUILDER) clean
fullclean:
	$(BUILDER) fullclean
	rm -rf $(RELEASE_DIR)
format:
	clang-format-19 -i $(SOURCES)
